@BusBookingSystem.API_HostAddress = http://localhost:5267

GET {{BusBookingSystem.API_HostAddress}}/api/depots
Accept: application/json

###

GET {{BusBookingSystem.API_HostAddress}}/api/trips
Accept: application/json

###
